import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  ptyCreate: (options) => ipcRenderer.invoke('pty:create', options),
  ptyWrite: (pid, data) => ipcRenderer.send('pty:write', { pid, data }),
  ptyResize: (pid, cols, rows) => ipcRenderer.send('pty:resize', { pid, cols, rows }),
  ptyKill: (pid) => ipcRenderer.invoke('pty:kill', pid),
  onPtyData: (cb) => ipcRenderer.on('pty:data', (_, { pid, data }) => cb(pid, data)),
  onPtyExit: (cb) => ipcRenderer.on('pty:exit', (_, info) => cb(info)),
  getHomedir: () => ipcRenderer.invoke('app:homedir'),
  fsReadDir: (dirPath) => ipcRenderer.invoke('fs:read-dir', { dirPath }),
  fsCreateFile: (filePath) => ipcRenderer.invoke('fs:create-file', { filePath }),
  fsCreateDir: (dirPath) => ipcRenderer.invoke('fs:create-dir', { dirPath }),
  fsRename: (oldPath, newPath) => ipcRenderer.invoke('fs:rename', { oldPath, newPath }),
  fsDelete: (targetPath) => ipcRenderer.invoke('fs:delete', { targetPath }),
  fsCopy: (srcPath, destDir) => ipcRenderer.invoke('fs:copy', { srcPath, destDir }),
  getCwd: () => ipcRenderer.invoke('fs:get-cwd'),
  fsSetRoot: (dirPath) => ipcRenderer.invoke('fs:set-root', { dirPath }),
  fsWatchDir: (dirPath) => ipcRenderer.invoke('fs:watch-dir', { dirPath }),
  fsUnwatchDir: (dirPath) => ipcRenderer.invoke('fs:unwatch-dir', { dirPath }),
  onFsDirChanged: (cb) => ipcRenderer.on('fs:dir-changed', (_, data) => cb(data)),
  windowGetPosition: () => ipcRenderer.invoke('window:get-position'),
  windowMove: (x, y) => ipcRenderer.send('window:move', { x, y }),
  tabsHasSavedState: () => ipcRenderer.invoke('tabs:has-saved-state'),
  tabsLoadSavedState: () => ipcRenderer.invoke('tabs:load-saved-state'),
  tabsDeleteSavedState: () => ipcRenderer.invoke('tabs:delete-saved-state'),
  tabsShowRestoreDialog: (tabCount) => ipcRenderer.invoke('tabs:show-restore-dialog', tabCount),
  tabsStateChanged: () => ipcRenderer.send('tabs:state-changed'),
  onTabsTriggerRestore: (cb) => ipcRenderer.on('tabs:trigger-restore', () => cb())
})
